export const NavigationList = {
  splash: 'Splash',
  welcome: 'Welcome',
  auth: 'Auth',
  login: 'Login',
  register: 'Register',
  otpVerification: 'OtpVerification',
  otpSuccess: 'OtpSuccess',
  forgotPassword: 'ForgotPassword',
  forgotPasswordSuccess: 'ForgotPasswordSuccess',
  home: 'Home',
  homeBottomNav: 'HomeBottomNav',
  patientList: 'Patient List',
  commingSoon: 'Comming Soon',
  profile: 'Profile',
  appoinmentDetails: 'AppoinmentDetails',
  addpatient: 'AddPatient',
  patientDetails: 'PatientDetails',
  bookingAppoinment: 'BookingAppoinment',
  patientProfile: 'PatientProfile',
};
