export const ADD_LOGIN_DETAILS = 'ADD_LOGIN_DETAILS';
export const REMOVE_LOGIN_DETAILS = 'REMOVE_LOGIN_DETAILS';
export const GET_LOGIN_DETAILS = 'GET_LOGIN_DETAILS';
export const IS_LOGIN = 'IS_LOGIN';
export const HOME_APPOINMENTS_FILTER = 'HOME_APPOINMENTS_FILTER';
